### ISSUE TITLE
Rename branch to main from mian

### ISSUE THREAD

**Issue by 71033** [ZU3AIRE/30-Days-of-JavaScript#13]
Please update the name of main branch.

**Comment by ZU3AIRE** [comment]
oh @71033 good catch let me update it

**Comment by ZU3AIRE** [comment]
The branch `mian` has renamed to `main`
Every local user will now have to run the following commands on their local git cli 
```bash
  git branch -m mian main
  git fetch origin
  git branch -u origin/main main
  git remote set-head origin -a
  ```

### Alternate 
Discard the local repo and clone again 😊
