### ISSUE TITLE
Rename bracnch's problem Number from 2703 to 2666

### ISSUE THREAD

**Issue by muhammad-mousa** [ZU3AIRE/30-Days-of-JavaScript#14]

**Comment by muhammad-mousa** [comment]
Please update the branch number from 2703 to 2666  
Branch Name:      2703-allow-one-function-call

**Comment by ZU3AIRE** [comment]
On it will close this comment shortly

**Comment by ZU3AIRE** [comment]
Every members will have to manually update their local environments. please run following commands in order to get synced up.
```bash
  git branch -m feature/2703-allow-one-function-call feature/2666-allow-one-function-call
  git fetch origin
  git branch -u origin/feature/2666-allow-one-function-call feature/2666-allow-one-function-call
  git remote set-head origin -a
 ```

### Alternate 
Discard old repo and clone new one 😊
